version: '3.7'
services:
  hydra:
    image: oryd/hydra:v1.11.7
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/hydra
        target: /etc/config/hydra
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.11.7
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  hydra-consent-ui:
    image: oryd/hydra-login-consent-node:v1.11.8 # Using the classic one, we don't need to modify it anymore...
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:
volumes:
  hydra-sqlite:
