version: '3.7'

services:

  ## Hydra ##

  hydra:
    image: oryd/hydra:v1.11.7
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.11.7
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  passport-ui-hydra:
    image: ga4gh/ga4gh-starter-kit-passport-ui-hydra
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet
  
  ## Kratos ##

  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1.pre.1-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command:
      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # kratos-selfservice-ui-node:
    # image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
    # environment:
    #   - KRATOS_PUBLIC_URL=http://kratos:4433/
    #   - KRATOS_ADMIN_URL=http://kratos:4434/
    #   - PORT=4455
    #   - SECURITY_MODE=
    #   - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    # networks:
    #   - intranet
    # restart: on-failure
    # ports:
    #   - "4455:4455"      

  passport-ui-kratos:
    image: ga4gh/ga4gh-starter-kit-passport-ui-kratos
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    ports:
      - "4455:4455"
    restart: unless-stopped
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1.pre.1-sqlite
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet
  
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  hydra-sqlite:
  kratos-sqlite:
