selfservice:
  flows:
    registration:
      after:
        password:
          hooks:
            - 
              hook: session
              config:
                url: https://ww.google.com
                method: POST
                body: file:///kratos-config/register.jsonnet
 